[en]
  languageName = "English"
  languageCode = "en-GB"
  weight = 10
  contentDir = "content_en"
  [en.params]
    languageISO = "EN"

[ca]
  languageName = "Català"
  languageCode = "ca"
  weight = 20
  contentDir = "content_ca"
  [ca.params]
    languageISO = "CA"

