baseURL = "https://disk-sentinel.github.io/"
title = "Disk Sentinel"
theme = "hugo-bootstrap-theme"

defaultContentLanguage = "ca"
defaultContentLanguageInSubdir = true

enableRobotsTXT = true
enableEmoji = true
disableHugoGeneratorInject = true

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[taxonomies]
  tag = "tags"
  category = "categories"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
